version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: crew-space-db
    ports:
      - "27017:27017"
    volumes:
      - crew-space-data:/data/db
    command: ["--replSet", "rs0"]
    healthcheck:
      test: test $$(mongosh --quiet --eval "db.adminCommand('ping').ok") -eq 1
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-init:
    image: mongo:6.0
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongosh --host mongodb --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongodb:27017\" }]
          })'
      "

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crew-space-server
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: crew-space-client
    depends_on:
      - server
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: pnpm dev

volumes:
  crew-space-data:
