name: CI/CD Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  unit:
    name: Lint, Format, and Unit Tests (Server & Client)
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      #====== Server ======#
      - name: Install server dependencies
        working-directory: server
        run: pnpm install

      - name: Lint Server
        working-directory: server
        run: pnpm lint

      - name: Check server format
        working-directory: server
        run: pnpm format:check

      - name: Run unit tests
        working-directory: server
        run: pnpm test:unit

      - name: Enforce code coverage thresholds
        working-directory: server
        run: pnpm test:unit:coverage

      #======= Client ======#
      - name: Install client dependencies
        working-directory: client
        run: pnpm install

      - name: Lint client
        working-directory: client
        run: pnpm lint

      - name: Check client format
        working-directory: client
        run: pnpm format:check

  integration:
    name: run integration test
    runs-on: ubuntu-latest
    needs: unit
    if: github.event.name == 'pull_request' && github.event.pull_request.base.ref == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install server dependencies
        working-directory: server
        run: pnpm install

      - name: Run integration tests
        working-directory: server
        run: pnpm test:integration
